#!/bin/bash

# Demo script for testing GitHub issue creation
# This script demonstrates how to test the GitHub integration

echo "🚀 Jira AI GitHub Integration Demo"
echo "=================================="
echo ""
echo "To test the GitHub integration:"
echo ""
echo "1. Start the backend server:"
echo "   cd jira-ai-web && node backend-proxy.js"
echo ""
echo "2. Open the web app:"
echo "   Open index.html in your browser"
echo ""
echo "3. Configure settings (click hamburger menu ☰):"
echo "   - Add your Azure API Key"
echo "   - Add your GitHub Personal Access Token"
echo "   - Set GitHub Repository (format: owner/repo)"
echo ""
echo "4. Generate a story:"
echo "   - Enter a task description"
echo "   - Click 'Generate Story'"
echo ""
echo "5. Select platforms:"
echo "   - Check 'Create GitHub Issue'"
echo "   - Optionally check 'Create Jira Ticket' too"
echo ""
echo "6. Set GitHub labels (optional):"
echo "   - Enter comma-separated labels (e.g., 'enhancement,feature')"
echo ""
echo "7. Click 'Create Issues'"
echo ""
echo "📝 Note: Make sure your GitHub token has 'repo' permissions!"
echo ""
echo "🔗 Example repositories to test with:"
echo "   - your-username/test-repo"
echo "   - your-org/project-name"
echo ""
echo "✅ The app will create issues in your selected platforms"
echo "   and show clickable links to view the created issues."
